# nginx.conf
#
# Nginx er dørvakten mellom internett og appen vår.
#
# REGEL:
#   /admin  → berre tilgjengeleg frå bedriftsnettverket (192.168.10.x)
#   /       → open for alle

server {
    listen 80;

    # ── ADMIN: berre for bedriften ──────────────────────
    location /admin {
    allow 172.18.0.0/16;
    allow 127.0.0.1;
    allow ::1;
    allow 10.200.128.0/22;
    allow 192.168.10.0/24;
    deny all;

    proxy_pass http://app:3000;
    proxy_set_header X-Real-IP $remote_addr;
}

    # ── ALT ANNA: open for alle ─────────────────────────
    location / {
        proxy_pass http://app:3000;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
